### ISSUE TITLE
unknown warning group '-Wimplicit-fallthrough='

### ISSUE THREAD

**Issue by bear24rw** [rue-ryuzaki/argparse#1]
I am getting this warning with clang 13.0.0 on macos

```
../libs/argparse/include/argparse/argparse.hpp:97:32: warning: unknown warning group '-Wimplicit-fallthrough=', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wimplicit-fallthrough="
                               ^
1 warning generated.
```
```
% clang++ --version
Homebrew clang version 13.0.0
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

**Comment by rue-ryuzaki** [comment]
This warning is fixed in the commit [22a20f2](https://github.com/rue-ryuzaki/argparse/commit/22a20f21a13b9b0f63834eb49fa05321be640645).

**Comment by bear24rw** [comment]
Awesome! Thanks for the quick fix and this amazing library!

**Comment by rue-ryuzaki** [comment]
Thank you! It's just a C++ variant of the python's ArgumentParser, [Python API support](https://github.com/rue-ryuzaki/argparse#argumentparser-objects-support).
If you used it in python, then you can easily get used to this parser in C++.
