### ISSUE TITLE
🐛 Attribute names for optional arguments

### ISSUE THREAD

**Issue by TrippyHank** [rue-ryuzaki/argparse#19]
### Description

Hi there!

It's been a while, happy holidays 👋

I recently came across an integration detail that does not conform to the specification.

It seems that it is not possible to use _internal values_ for attribute names in calls like `args.exists("long_option")` instead of `args.exists("--long-option")` for an argument specified as `--long-option`.

Excerpt from https://docs.python.org/3/library/argparse.html#dest

> For optional argument actions, the value of **dest** is normally inferred from the option strings. [ArgumentParser](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser) generates the value of **dest** by taking the first long option string and stripping away the initial `--` string. If no long option strings were supplied, **dest** will be derived from the first short option string by stripping the initial `-` character. Any internal `-` characters will be converted to `_` characters to make sure the string is a valid attribute name.

### Reproduction steps

Make a call to a function that requires an attribute name for an optional compound argument using _explicit_ and _internal_ values

### Expected vs. actual results

I expected the calls to accept this subtlety

### Compiler and operating system

g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

### Library version

1.6.5

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/rue-ryuzaki/argparse/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/rue-ryuzaki/argparse#execute-unit-tests).

**Comment by rue-ryuzaki** [comment]
@TrippyHank Hi!

Please, check pull request #20

**Comment by rue-ryuzaki** [comment]
```args.exists("long_option")``` should work for argument ```--long-option```

```args.exists("--long-option")``` and ```args.exists("long-option")``` will remain to maintain compatibility
