### ISSUE TITLE
✨ add support for implicit values

### ISSUE THREAD

**Issue by TrippyHank** [rue-ryuzaki/argparse#4]
Hello there!

A very useful library 👏

Do you plan to incorporate _implicit value_ support in the near future?

These **implicit values** behave like flags and allow you to use a predefined value or specify a custom one on activation.

This is slightly different from a default value, since when the argument is not specified on the command line, no value (or a null value) is assigned to the argument.

```shell
./mybin
# where arg is disabled

./mybin --arg
# where arg is "mypredefinedvalue"

./mybin --arg mycustomvalue
# where arg is "mycustomvalue"
```

This is an alternative to having 2 arguments for this task using a default and a flag, such as:

```shell
./mybin --no-arg
# where arg is disabled

./mybin
# where arg is "mypredefinedvalue"

./mybin --arg mycustomvalue
# where arg is "mycustomvalue"
```

**Comment by rue-ryuzaki** [comment]
@TrippyHank Hello. I recently added code to handle a similar situation. I will try to implement it later.

**Comment by rue-ryuzaki** [comment]
@TrippyHank check 4-add-support-for-implicit-values branch
I tested with the following code:
```cpp
auto parser = argparse::ArgumentParser("mybin");

parser.add_argument("--arg").implicit_value("mypredefinedvalue").nargs("?");

std::cout << parser.parse_args("").get<std::string>("arg") << std::endl;
std::cout << parser.parse_args("--arg").get<std::string>("arg") << std::endl;
std::cout << parser.parse_args("--arg mycustomvalue").get<std::string>("arg") << std::endl;
```

**Comment by rue-ryuzaki** [comment]
Another way:
```cpp
auto parser = argparse::ArgumentParser("mybin");

parser.add_argument("--arg").nargs("?").const_value("mypredefinedvalue");

std::cout << parser.parse_args("").get<std::string>("arg") << std::endl;
std::cout << parser.parse_args("--arg").get<std::string>("arg") << std::endl;
std::cout << parser.parse_args("--arg mycustomvalue").get<std::string>("arg") << std::endl;
```
have the same output
```

mypredefinedvalue
mycustomvalue
```

**Comment by TrippyHank** [comment]
@rue-ryuzaki Awesome, thanks!

**Comment by rue-ryuzaki** [comment]
@TrippyHank This feature will be added in version 1.4.1 (release ~16-17th April)
