### ISSUE TITLE
🐛 arguments parsing should be reviewed

### ISSUE THREAD

**Issue by TrippyHank** [rue-ryuzaki/argparse#6]
Hello!

Implicit values (from 80ab3cce732d888589807b5052e203c40ca2766d ) do not work if they are followed by other positional arguments (or subparsers), the following value might have to be compared to next available arguments in order to assert if that's a custom value or another argument.

Given a parser with an implicit value optional argument `--arg` and a positional argument `value`:

```shell
./mybin --arg mycustomvalue 42
# works
./mybin --arg 42
# fails
```

The same behavior occurs in the context of [subparsers](https://github.com/rue-ryuzaki/argparse#subparsers-example).

Given a parser with an implicit value optional argument `--arg` and a subparser `a`:

```shell
./mybin --arg mycustomvalue a
# works
./mybin --arg a
# fails

**Comment by rue-ryuzaki** [comment]
@TrippyHank Hi!
Yes, it doesn't work as expected. But this is the original logic for parsing command line arguments.
It will take some time to change the parsing process.

**Comment by rue-ryuzaki** [comment]
@TrippyHank 
I started to rewrite the algorithm, but there were doubts about the implementation.
example:
```cpp
auto parser = argparse::ArgumentParser(argc, argv);

parser.add_argument("bar");
parser.add_argument("--baz").action("store_true");
parser.add_argument("--foo").nargs("?").implicit_value("foo");

auto const args = parser.parse_args();

std::cout << args.to_string() << std::endl;
```
in current version we have:
```
> [1] parse_args("--foo b")
Error
> [2] parse_args("--foo b bar")
Namespace(bar='bar', baz=false, foo='b')
> [3] parse_args("--foo b --baz bar")
Namespace(bar='bar', baz=true, foo='b')
> [4] parse_args("--foo b bar --baz")
Namespace(bar='bar', baz=true, foo='b')
> [5] parse_args("--foo --baz bar")
Namespace(bar='bar', baz=true, foo='foo') 
```
I can fix [1], but it will break [2]. I can add more test cases if needed (e.g. if baz also will have implicit value).
I don't know what to do with it yet.

**Comment by TrippyHank** [comment]
We might be able to extract the parsing logic from [CPython](https://github.com/python/cpython/blob/944fffee8916cb94321fa33cd3a43f4108717746/Lib/argparse.py#L1840-L1842)

**mybin.py**
```python
import argparse
import sys

parser = argparse.ArgumentParser()

parser.add_argument("bar")
parser.add_argument("--baz", action="store_true")
parser.add_argument("--foo", nargs="?", const="myconstvalue")

print("args:", sys.argv[1:])
print("parsed:", parser.parse_args(sys.argv[1:]))
```

Below are few outputs we can get from the python `argparse` package for such a parser:

```shell
python3 mybin.py --foo abc a --baz
# args: ['--foo', 'abc', 'a', '--baz']
# parsed: Namespace(bar='a', baz=True, foo='abc')

python3 mybin.py a --foo --baz
# args: ['a', '--foo', '--baz']
# parsed: Namespace(bar='a', baz=True, foo='myconstvalue')
```

There's still a logical way to combine arguments

**Comment by rue-ryuzaki** [comment]
parser logic matches the original:
```cpp
auto parser = argparse::ArgumentParser(argc, argv);

parser.add_argument("bar");
parser.add_argument("--baz").action("store_true");
parser.add_argument("--foo").nargs("?").implicit_value("myconstvalue");

std::cout << "args: --foo abc a --baz\nparsed: " << parser.parse_args("--foo abc a --baz").to_string() << std::endl;
std::cout << "args: a --foo --baz\nparsed: "     << parser.parse_args("a --foo --baz").to_string()     << std::endl;
std::cout << "args: --baz a\nparsed: "           << parser.parse_args("--baz a").to_string()           << std::endl;
```
output:
```
args: --foo abc a --baz
parsed: Namespace(bar='a', baz=true, foo='abc')
args: a --foo --baz
parsed: Namespace(bar='a', baz=true, foo='myconstvalue')
args: --baz a
parsed: Namespace(bar='a', baz=true, foo=None)
```

**Comment by rue-ryuzaki** [comment]
but originally the question was regarding the following example (implicit value in python):
```py
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('arg', nargs='?', const='mypredefinedvalue')
parser.add_argument('b')

print(parser.parse_args("mycustomvalue b".split()))
print(parser.parse_args("b".split()))
```
output:
```
Namespace(arg='mycustomvalue', b='b')
Namespace(arg=None, b='b')
```
in last result arg have default None value, not const "mypredefinedvalue" value

**Comment by rue-ryuzaki** [comment]
If parse "b --arg" instead of "--arg b" all be ok:
```
// in python
Namespace(arg='mypredefinedvalue', b='b')
// in c++
Namespace(b='b', arg='mypredefinedvalue')
```

**Comment by TrippyHank** [comment]
You're right, my bad 🤦

Regarding subparsers, should there be some form of inheritance of the parent's arguments so that they can be delegated to subparsers ?

Conflicting arguments (i.e. `--arg` added to both the parent and the subparser) might prioritize the subparser argument for granularity.

Given `sub` is a subparser to destination `b`:

```shell
./mybin sub --arg
Namespace(arg='mypredefinedvalue', b='sub')
```

Since this is not possible:

```shell
./mybin --arg sub
# does not work since the parser takes "sub" as a value to `--arg`
```

> Another path would be to compare the value received for `--arg` to available subparsers values. For example, since `sub` is a valid argument to `b` it should be prioritized over the `--arg` optional argument.

**Comment by rue-ryuzaki** [comment]
> in current version we have:
> 
> ```
> > [1] parse_args("--foo b")
> Error
> > [2] parse_args("--foo b bar")
> Namespace(bar='bar', baz=false, foo='b')
> > [3] parse_args("--foo b --baz bar")
> Namespace(bar='bar', baz=true, foo='b')
> > [4] parse_args("--foo b bar --baz")
> Namespace(bar='bar', baz=true, foo='b')
> > [5] parse_args("--foo --baz bar")
> Namespace(bar='bar', baz=true, foo='foo') 
> ```
> 
> I can fix [1], but it will break [3]. I can add more test cases if needed (e.g. if baz also will have implicit value). I don't know what to do with it yet.

the parser has a certain algorithm for processing positional arguments (mixed positional arguments with nargs = "*", "?", "+").
I thought I could remember the current value of the optional argument beforehand (with nargs = "?" and maybe "*"), and check how it will be parsed with following positional arguments. in some cases it will help, but in others it won't.

Yes, with subparsers, it's not so easy to come up with a workaround

**Comment by rue-ryuzaki** [comment]
> Regarding subparsers, should there be some form of inheritance of the parent's arguments so that they can be delegated after subparsers in the command line?

more likely if you create same argument into all subparser's parsers
should somehow work:
```cpp
auto parser = argparse::ArgumentParser().fromfile_prefix_chars("@");

parser.add_argument("--arg").nargs("?").const_value("mypredefinedvalue");
parser.add_argument("b");

auto& subparsers = parser.add_subparsers().dest("cmd").help("sub-command help");

auto& parser_a = subparsers.add_parser("a").help("a help");
parser_a.add_argument("bar").help("bar help");
parser_a.add_argument("--arg").nargs("?").const_value("mypredefinedvalue");

auto& parser_b = subparsers.add_parser("b").help("b help");
parser_b.add_argument("--baz").choices("XYZ").help("baz help");
parser_b.add_argument("--arg").nargs("?").const_value("mypredefinedvalue");
```

**Comment by TrippyHank** [comment]
That's exactly my workaround for now 👷

It would be handy to have a `parents()` method on the subparser to avoid such repetition

**Comment by rue-ryuzaki** [comment]
Hm... I see it's possible to set parents for subparsers in python's argparse [link](https://stackoverflow.com/questions/24666197/argparse-combining-parent-parser-subparsers-and-default-values)
```python
import argparse

# this serves as a parent parser
base_parser = argparse.ArgumentParser(add_help=False)
base_parser.add_argument('-n', help='number', type=int, default=42)

# this is the top level parser
parser = argparse.ArgumentParser(description='bla bla', parents=[base_parser])

# subparsers
subparsers = parser.add_subparsers()

subparser1 = subparsers.add_parser('a', help='subparser 1', parents=[base_parser])
subparser2 = subparsers.add_parser('b', help='subparser 2', parents=[base_parser])

args = parser.parse_args()
print(args)
```

**Comment by TrippyHank** [comment]
It works on my side
Good job 🍻

**Comment by rue-ryuzaki** [comment]
Parsing logic updated in v1.5
