### ISSUE TITLE
Allow share dest storage

### ISSUE THREAD

**Issue by rysson** [rue-ryuzaki/argparse#9]
### Description

First, thanks for awesome library. I use Python argparse a lot, then now I can use it in C++. 

I have similar issue to #4, specially the second case.
The goal is use default value without any option and allow override it or disable it (or change same predefined).

```
./mybin
# a) default arg "a"

./mybin --no-arg
# b) where arg is disabled, set to "b" for better view

./mybin --arg x
# x) where custom arg is "x"
```

Python version.
```python
p = argparse.ArgumentParser()
p.add_argument('--arg', default='a')
# _StoreAction(option_strings=['--arg'], dest='arg', nargs=None, const=None, default='a', type=None, choices=None, required=False, help=None, metavar=None)
p.add_argument('--no-arg', dest='arg', action='store_const', const='b')
# _StoreConstAction(option_strings=['--no-arg'], dest='arg', nargs=0, const='b', default=None, type=None, choices=None, required=False, help=None, metavar=None)

p.parse_args(''.split())
# Namespace(arg='a')

p.parse_args('--arg x'.split())
# Namespace(arg='x')

p.parse_args('--no-arg'.split())
# Namespace(arg='b')
```

I have a problem with `dest`. There is a conflict or second argument overrides the first.
Of course I can use an another name add add `if` to override `dest` in my code after parsing. Than it's not so important issue.
Just note Python differs.

### Reproduction steps

Compile and run.

#### Actual results
For `dest("--arg")` I have:
```
argparse::ArgumentError: argument --no-arg: conflicting dest string: --arg
```

For `dest("arg")` I have:
```
./mybin 
(empty)  arg is ''

./mybin --no-arg
(exists) arg is 'b'

./mybin --arg x
(empty)  arg is ''
```

#### Expected results
In both cases.
```
./mybin 
(exists) arg is 'a'

./mybin --no-arg
(exists) arg is 'b'

./mybin --arg x
(exists)  arg is 'x'
```

### Minimal code example

```Shell
#include "argparse.hpp"

int main(int argc, char *argv[])
{
	auto parser = argparse::ArgumentParser(argc, argv);
	parser.add_argument("--arg").default_value("a");
	parser.add_argument("--no-arg").action("store_const").dest("arg").const_value("b");
	auto const args = parser.parse_args();
	std::cout << (args.exists("arg") ? "(exists)" : "(empty) ") << " arg is '" << args.get<std::string>("arg") << "'" << std::endl;
	return 0;
}
```

### Error messages

```Shell
argparse::ArgumentError: argument --no-arg: conflicting dest string: --arg
```

### Compiler and operating system

c++ -o mybin aa.cc
Debian testing.

### Library version

1.6.4

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/rue-ryuzaki/argparse/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/rue-ryuzaki/argparse#execute-unit-tests).

**Comment by rue-ryuzaki** [comment]
Hi, @rysson! Thanks for this issue!

Clearly, for this case, the argparse::BooleanOptionalAction action is not suitable...
I really did not want to make a "dest" resolving, but still it needs to be done

**Comment by rue-ryuzaki** [comment]
@rysson  please check latest version from the ```develop``` branch from this commit [1dbf44d](https://github.com/rue-ryuzaki/argparse/commit/1dbf44d47a4ae062adf8ff82d44b2c517f305723)

You must to set the same "dest" value for arguments, which value you want to share:
```cpp
auto parser = argparse::ArgumentParser();
parser.add_argument("--arg").dest("arg").default_value("a");
parser.add_argument("--no-arg").action("store_const").dest("arg").const_value("b");
auto vars = { "", "--no-arg", "--arg x" };
for (auto const& var : vars) {
    auto const args = parser.parse_args(var);
    std::cout << (args.exists("arg") ? "(exists)" : "(empty) ") << " arg is '" << args.get<std::string>("arg") << "'" << std::endl;
}
```
will have:
```sh
(exists) arg is 'a'
(exists) arg is 'b'
(exists) arg is 'x'
```

**Comment by rysson** [comment]
It works as chram. Awesome!

`dest("arg")` in `--arg` is OK. It takes code more clear.

Thank you a lot!

**Comment by rysson** [comment]
Sorry I missed 

> there are still some bugs, I'm working on them now

**Comment by rue-ryuzaki** [comment]
I try to fix this example (fixed, but don't commited):
```cpp
auto parser = argparse::ArgumentParser(argc, argv);
parser.add_argument("--no-arg").action("store_const").dest("arg").const_value("b");
parser.add_argument("--arg").dest("arg").default_value("a");
auto vars = { "", "--no-arg", "--arg x" };
for (auto const& var : vars) {
    auto const args = parser.parse_args(var);
    std::cout << (args.exists("arg") ? "(exists)" : "(empty) ") << " arg is '" << args.get<std::string>("arg") << "'" << std::endl;
}
```
and if both --arg and --no-arg are passed:
```cpp
auto const args = parser.parse_args("--arg x --no-arg");
std::cout << (args.exists("arg") ? "(exists)" : "(empty) ") << " arg is '" << args.get<std::string>("arg") << "'" << std::endl;
```

**Comment by rysson** [comment]
It's OK IMHO.
The same in Python

```python
p = argparse.ArgumentParser(); p.add_argument('--arg', default='a')
p.parse_args('--arg x --arg y'.split())
# Namespace(arg='y')
```

```python
p = argparse.ArgumentParser(); p.add_argument('--arg', default='a')
p.add_argument('--no-arg', dest='arg', action='store_const', const='b')
p.parse_args('--arg x --no-arg'.split())
# Namespace(arg='b')
```

Both cases are similar.

If user wants to exclude those options they can use exclusive group.

**Comment by rue-ryuzaki** [comment]
Seems to work...
check latest version from the ```develop``` branch from this commit [4c76d34](https://github.com/rue-ryuzaki/argparse/commit/4c76d34031fae4b68dd05c7100a2329144e9e27c)

**Comment by rysson** [comment]
Yes, seems to work :-D
